%% （二）、输出最优参数情况下的收盘价及动态权益变动情况图及保存
%% 1、设置表标题
tfirst='最优参数';                                      % 图标题固定部分一
tsecond='情况下的收盘价及动态权益变动情况图';               % 图标题固定部分二
fgtitle=[tfirst,'(',num2str(BestParameter1),'-',num2str(BestParameter2),')',tsecond]   % 图标题可变参数部分

%% 绘图
scrsz=get(0,'ScreenSize');      %获取当前屏幕大小
figure('Position',[scrsz(3)*1/4 scrsz(4)*1/6 scrsz(3)*4/5 scrsz(4)]*3/4); %设置图版大小
plotyy(times,DynamicEquity,times,ClosePrice);
hold on;
text(ExtrHiDynaDate,ExtrHiDyna,'\leftarrow最大动态权益','Color','blue');
hold on;
text(times(20),100000,['总收益率',num2str(NetReturnRatio)],'Color','green','FontWeight','Bold');
hold on;
dateaxis('x',12)                                        %更改x轴标记格式
legend('DynamicEquity','ClosePrice','Location','Best');    %添加图例
title(fgtitle,'FontWeight','Bold');    %添加表头，并设置字体格式
hold on;

%% 保存图
SJpgfileName=['output2_MA_',ContractCode,'_',posm,'_',num2str(mperiods1),'min最优参数情况下的收盘价及动态权益变动情况图.jpg'];                   % 保存Jpg文件的命名
saveas(1,['F:\tradingMAresult\',SJpgfileName])


%% （三）、输出报告
header3={'买入移动周期';'卖出移动周期';'测试起始时间';'测试结束时间';'K线个数';'K线周期';'总盈亏';...
    '总收益率';'最终权益';'总盈利';'总亏损';...
    '交易次数';'盈利次数';'亏损次数';'胜率';'亏损比例';...
    '平均盈利';'平均亏损';'最大回撤比';...
    '最大回撤时间';'最大权益';'最小权益';'最大权益日期';...
    '最大权益K线距离';'最大权益实际时间距离';...
    '权益最长未创新高K线周期';'权益最长未创新高实际周期';...
    '权益最长未创新高起始时间';'权益最长未创新高结束时间'};                   % 表格标题行
if mperiods1==0
    zuiyou=[num2cell(BestParameter1);num2cell(BestParameter2);cellstr(datestr(times(1),'dd/mm/yyyy'));...
        cellstr(datestr(times(end),'dd/mm/yyyy'));num2cell(length(ClosePrice));num2cell(mperiods1);num2cell(CumNetMarginFinal);...
        num2cell(NetReturnRatio);num2cell(DynamicEquityFinal);num2cell(CumWinNetMarginFinal);num2cell(CumLoseNetMarginFinal);...
        num2cell(ClosePosNum);num2cell(WinNum);num2cell(LoseNum);num2cell(WinRatio);num2cell(LoseRatio);...
        num2cell(AverWinNetMargin);num2cell(AverLoseNetMargin);num2cell(MaxBackRatio);...
        cellstr(datestr(MaxBackRatioDate,'dd/mm/yyyy'));num2cell(ExtrHiDyna);num2cell(ExtrLowDyna);cellstr(datestr(ExtrHiDynaDate,'dd/mm/yyyy'));...
        num2cell(ExtrHiDynatoEnd);num2cell(ExtrHiDynatoEndactu);...
        num2cell(maxkperiod);num2cell(maxactuperiod);...
        cellstr(datestr(maxactuperiodStart,'dd/mm/yyyy'));cellstr(datestr(maxactuperiodEnd,'dd/mm/yyyy'))];      
else
    zuiyou=[num2cell(BestParameter1);num2cell(BestParameter2);cellstr(datestr(times(1),'dd/mm/yyyy HH:MM:SS'));...
        cellstr(datestr(times(end),'dd/mm/yyyy HH:MM:SS'));num2cell(length(ClosePrice));num2cell(mperiods1);num2cell(CumNetMarginFinal);...
        num2cell(NetReturnRatio);num2cell(DynamicEquityFinal);num2cell(CumWinNetMarginFinal);num2cell(CumLoseNetMarginFinal);...
        num2cell(ClosePosNum);num2cell(WinNum);num2cell(LoseNum);num2cell(WinRatio);num2cell(LoseRatio);...
        num2cell(AverWinNetMargin);num2cell(AverLoseNetMargin);num2cell(MaxBackRatio);...
        cellstr(datestr(MaxBackRatioDate,'dd/mm/yyyy HH:MM:SS'));num2cell(ExtrHiDyna);num2cell(ExtrLowDyna);cellstr(datestr(ExtrHiDynaDate,'dd/mm/yyyy HH:MM:SS'));...
        num2cell(ExtrHiDynatoEnd);num2cell(ExtrHiDynatoEndactu);...
        num2cell(maxkperiod);num2cell(maxactuperiod);...
        cellstr(datestr(maxactuperiodStart,'dd/mm/yyyy HH:MM:SS'));cellstr(datestr(maxactuperiodEnd,'dd/mm/yyyy HH:MM:SS'))];                 
end
xlswrite(['F:\tradingMAresult\',SExcelfileName],[header3,zuiyou],'最优综合评价指标');


